// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AclService ACL 管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * CreateAcl 创建 ACL 规则
 */
export function CreateAcl(subject: string, policies: model$0.AclPolicy[], description: string): $CancellablePromise<void> {
    return $Call.ByID(2893345411, subject, policies, description);
}

/**
 * CreateUser 创建 ACL 用户
 */
export function CreateUser(username: string, password: string, userType: string): $CancellablePromise<void> {
    return $Call.ByID(2984243154, username, password, userType);
}

/**
 * DeleteAcl 删除 ACL 规则
 */
export function DeleteAcl(subject: string): $CancellablePromise<void> {
    return $Call.ByID(4232056006, subject);
}

/**
 * DeleteUser 删除 ACL 用户
 */
export function DeleteUser(username: string): $CancellablePromise<void> {
    return $Call.ByID(2349313253, username);
}

/**
 * ListAcls 列出所有 ACL 规则
 */
export function ListAcls(): $CancellablePromise<(model$0.AclRule | null)[]> {
    return $Call.ByID(1958552460).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListUsers 列出所有 ACL 用户
 */
export function ListUsers(): $CancellablePromise<(model$0.AclUser | null)[]> {
    return $Call.ByID(3010979359).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * UpdateUser 更新 ACL 用户
 */
export function UpdateUser(username: string, password: string, userType: string, userStatus: string): $CancellablePromise<void> {
    return $Call.ByID(3803420895, username, password, userType, userStatus);
}

// Private type creation functions
const $$createType0 = model$0.AclRule.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.AclUser.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
