// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AclService ACL 管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * CreateOrUpdateAccessConfig 创建或更新 ACL 访问配置
 */
export function CreateOrUpdateAccessConfig(accessKey: string, secretKey: string, whiteRemoteAddress: string, isAdmin: boolean, defaultTopicPerm: string, defaultGroupPerm: string, topicPerms: string[], groupPerms: string[]): $CancellablePromise<void> {
    return $Call.ByID(4221023897, accessKey, secretKey, whiteRemoteAddress, isAdmin, defaultTopicPerm, defaultGroupPerm, topicPerms, groupPerms);
}

/**
 * DeleteAccessConfig 删除 ACL 访问配置
 */
export function DeleteAccessConfig(accessKey: string): $CancellablePromise<void> {
    return $Call.ByID(3087561186, accessKey);
}

/**
 * GetAclEnabled 检查 Broker 是否启用 ACL
 */
export function GetAclEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3015424318);
}

/**
 * GetAclVersion 获取 ACL 配置版本信息
 */
export function GetAclVersion(): $CancellablePromise<model$0.AclVersionInfo | null> {
    return $Call.ByID(1963108919).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateGlobalWhiteAddrs 更新全局白名单地址
 */
export function UpdateGlobalWhiteAddrs(addrs: string[]): $CancellablePromise<void> {
    return $Call.ByID(3005303316, addrs);
}

// Private type creation functions
const $$createType0 = model$0.AclVersionInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
