// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClusterService 集群状态服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * GetBrokerDetail 获取 Broker 详情
 */
export function GetBrokerDetail(brokerAddr: string): $CancellablePromise<model$0.BrokerNode | null> {
    return $Call.ByID(4188423809, brokerAddr).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetBrokers 获取 Broker 列表
 */
export function GetBrokers(): $CancellablePromise<(model$0.BrokerNode | null)[]> {
    return $Call.ByID(861100489).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetClusterInfo 获取集群信息
 */
export function GetClusterInfo(): $CancellablePromise<model$0.ClusterInfo | null> {
    return $Call.ByID(3432418489).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetClusterSummary 获取集群概览统计
 */
export function GetClusterSummary(): $CancellablePromise<model$0.ClusterSummary | null> {
    return $Call.ByID(133623647).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetNameServers 获取 NameServer 列表
 */
export function GetNameServers(): $CancellablePromise<(model$0.NameServerNode | null)[]> {
    return $Call.ByID(2506280570).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * RefreshBrokerStats 刷新 Broker 统计信息
 */
export function RefreshBrokerStats(brokerAddr: string): $CancellablePromise<model$0.BrokerNode | null> {
    return $Call.ByID(1816574962, brokerAddr).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.BrokerNode.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.ClusterInfo.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = model$0.ClusterSummary.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = model$0.NameServerNode.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType8);
