// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClusterService 集群状态服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * GetBrokerDetail 获取 Broker 详情
 * @param {string} brokerAddr
 * @returns {$CancellablePromise<model$0.BrokerNode | null>}
 */
export function GetBrokerDetail(brokerAddr) {
    return $Call.ByID(4188423809, brokerAddr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetBrokers 获取 Broker 列表
 * @returns {$CancellablePromise<(model$0.BrokerNode | null)[]>}
 */
export function GetBrokers() {
    return $Call.ByID(861100489).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetClusterInfo 获取集群信息
 * @returns {$CancellablePromise<model$0.ClusterInfo | null>}
 */
export function GetClusterInfo() {
    return $Call.ByID(3432418489).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetClusterSummary 获取集群概览统计
 * @returns {$CancellablePromise<model$0.ClusterSummary | null>}
 */
export function GetClusterSummary() {
    return $Call.ByID(133623647).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetNameServers 获取 NameServer 列表
 * @returns {$CancellablePromise<(model$0.NameServerNode | null)[]>}
 */
export function GetNameServers() {
    return $Call.ByID(2506280570).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * RefreshBrokerStats 刷新 Broker 统计信息
 * @param {string} brokerAddr
 * @returns {$CancellablePromise<model$0.BrokerNode | null>}
 */
export function RefreshBrokerStats(brokerAddr) {
    return $Call.ByID(1816574962, brokerAddr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = model$0.BrokerNode.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.ClusterInfo.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = model$0.ClusterSummary.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = model$0.NameServerNode.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType8);
