// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService 连接管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * AddConnection 添加新连接
 */
export function AddConnection(name: string, env: string, nameServer: string, timeoutSec: number, enableACL: boolean, accessKey: string, secretKey: string, remark: string): $CancellablePromise<model$0.Connection | null> {
    return $Call.ByID(1015835892, name, env, nameServer, timeoutSec, enableACL, accessKey, secretKey, remark).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Connect 连接指定连接
 */
export function Connect(id: number): $CancellablePromise<void> {
    return $Call.ByID(1510905961, id);
}

/**
 * ConnectDefault 连接默认连接
 */
export function ConnectDefault(): $CancellablePromise<void> {
    return $Call.ByID(896157434);
}

/**
 * DeleteConnection 删除连接
 */
export function DeleteConnection(id: number): $CancellablePromise<void> {
    return $Call.ByID(2600995934, id);
}

/**
 * GetConnection 获取单个连接配置
 */
export function GetConnection(id: number): $CancellablePromise<model$0.Connection | null> {
    return $Call.ByID(2854844575, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetConnections 获取所有连接配置
 */
export function GetConnections(): $CancellablePromise<(model$0.Connection | null)[]> {
    return $Call.ByID(3410582404).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SetDefaultConnection 设置默认连接
 */
export function SetDefaultConnection(id: number): $CancellablePromise<void> {
    return $Call.ByID(654081588, id);
}

/**
 * TestConnection 测试连接
 */
export function TestConnection(id: number): $CancellablePromise<string> {
    return $Call.ByID(1327143561, id);
}

/**
 * UpdateConnection 更新连接配置
 */
export function UpdateConnection(id: number, name: string, env: string, nameServer: string, timeoutSec: number, enableACL: boolean, accessKey: string, secretKey: string, remark: string): $CancellablePromise<model$0.Connection | null> {
    return $Call.ByID(3171807668, id, name, env, nameServer, timeoutSec, enableACL, accessKey, secretKey, remark).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.Connection.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
