// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService 连接管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * AddConnection 添加新连接
 * @param {string} name
 * @param {string} env
 * @param {string} nameServer
 * @param {number} timeoutSec
 * @param {boolean} enableACL
 * @param {string} accessKey
 * @param {string} secretKey
 * @param {string} remark
 * @returns {$CancellablePromise<model$0.Connection | null>}
 */
export function AddConnection(name, env, nameServer, timeoutSec, enableACL, accessKey, secretKey, remark) {
    return $Call.ByID(1015835892, name, env, nameServer, timeoutSec, enableACL, accessKey, secretKey, remark).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Connect 连接指定连接
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function Connect(id) {
    return $Call.ByID(1510905961, id);
}

/**
 * ConnectDefault 连接默认连接
 * @returns {$CancellablePromise<void>}
 */
export function ConnectDefault() {
    return $Call.ByID(896157434);
}

/**
 * DeleteConnection 删除连接
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConnection(id) {
    return $Call.ByID(2600995934, id);
}

/**
 * Disconnect 断开指定连接
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect(id) {
    return $Call.ByID(3243007643, id);
}

/**
 * GetConnection 获取单个连接配置
 * @param {number} id
 * @returns {$CancellablePromise<model$0.Connection | null>}
 */
export function GetConnection(id) {
    return $Call.ByID(2854844575, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetConnections 获取所有连接配置
 * @returns {$CancellablePromise<(model$0.Connection | null)[]>}
 */
export function GetConnections() {
    return $Call.ByID(3410582404).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SetDefaultConnection 设置默认连接
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultConnection(id) {
    return $Call.ByID(654081588, id);
}

/**
 * TestConnection 测试连接
 * @param {number} id
 * @returns {$CancellablePromise<string>}
 */
export function TestConnection(id) {
    return $Call.ByID(1327143561, id);
}

/**
 * UpdateConnection 更新连接配置
 * @param {number} id
 * @param {string} name
 * @param {string} env
 * @param {string} nameServer
 * @param {number} timeoutSec
 * @param {boolean} enableACL
 * @param {string} accessKey
 * @param {string} secretKey
 * @param {string} remark
 * @returns {$CancellablePromise<model$0.Connection | null>}
 */
export function UpdateConnection(id, name, env, nameServer, timeoutSec, enableACL, accessKey, secretKey, remark) {
    return $Call.ByID(3171807668, id, name, env, nameServer, timeoutSec, enableACL, accessKey, secretKey, remark).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = model$0.Connection.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
