// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConsumerService 消费者组服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * CreateConsumerGroup 创建消费者组
 * @param {string} group
 * @param {string} brokerAddr
 * @param {string} consumeMode
 * @param {number} maxRetry
 * @returns {$CancellablePromise<void>}
 */
export function CreateConsumerGroup(group, brokerAddr, consumeMode, maxRetry) {
    return $Call.ByID(91031836, group, brokerAddr, consumeMode, maxRetry);
}

/**
 * DeleteConsumerGroup 删除消费者组
 * @param {string} group
 * @param {string} brokerAddr
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConsumerGroup(group, brokerAddr) {
    return $Call.ByID(4171083873, group, brokerAddr);
}

/**
 * GetConsumeStats 获取消费统计信息
 * @param {string} groupName
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetConsumeStats(groupName) {
    return $Call.ByID(1667646038, groupName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetConsumerClients 获取消费者客户端列表
 * @param {string} groupName
 * @returns {$CancellablePromise<model$0.GroupClient[]>}
 */
export function GetConsumerClients(groupName) {
    return $Call.ByID(1977653181, groupName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetConsumerGroupDetail 获取消费者组详情
 * @param {string} groupName
 * @returns {$CancellablePromise<model$0.ConsumerGroupItem | null>}
 */
export function GetConsumerGroupDetail(groupName) {
    return $Call.ByID(1876345635, groupName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetConsumerGroups 获取所有消费者组列表
 * @returns {$CancellablePromise<(model$0.ConsumerGroupItem | null)[]>}
 */
export function GetConsumerGroups() {
    return $Call.ByID(1865015347).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ResetOffset 重置消费位点
 * @param {string} group
 * @param {string} topic
 * @param {number} timestamp
 * @param {boolean} force
 * @returns {$CancellablePromise<void>}
 */
export function ResetOffset(group, topic, timestamp, force) {
    return $Call.ByID(1452742991, group, topic, timestamp, force);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = model$0.GroupClient.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.ConsumerGroupItem.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
