// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConsumerService 消费者组服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * CreateConsumerGroup 创建消费者组
 */
export function CreateConsumerGroup(group: string, brokerAddr: string, consumeMode: string, maxRetry: number): $CancellablePromise<void> {
    return $Call.ByID(91031836, group, brokerAddr, consumeMode, maxRetry);
}

/**
 * DeleteConsumerGroup 删除消费者组
 */
export function DeleteConsumerGroup(group: string, brokerAddr: string): $CancellablePromise<void> {
    return $Call.ByID(4171083873, group, brokerAddr);
}

/**
 * GetConsumeStats 获取消费统计信息
 */
export function GetConsumeStats(groupName: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1667646038, groupName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetConsumerClients 获取消费者客户端列表
 */
export function GetConsumerClients(groupName: string): $CancellablePromise<model$0.GroupClient[]> {
    return $Call.ByID(1977653181, groupName).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetConsumerGroupDetail 获取消费者组详情
 */
export function GetConsumerGroupDetail(groupName: string): $CancellablePromise<model$0.ConsumerGroupItem | null> {
    return $Call.ByID(1876345635, groupName).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetConsumerGroups 获取所有消费者组列表
 */
export function GetConsumerGroups(): $CancellablePromise<(model$0.ConsumerGroupItem | null)[]> {
    return $Call.ByID(1865015347).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ResetOffset 重置消费位点
 */
export function ResetOffset(group: string, topic: string, timestamp: number, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(1452742991, group, topic, timestamp, force);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = model$0.GroupClient.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.ConsumerGroupItem.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
