// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MessageService 消息查询服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * GetMessageDetail 获取消息详情
 */
export function GetMessageDetail(topic: string, msgID: string): $CancellablePromise<model$0.MessageItem | null> {
    return $Call.ByID(826218736, topic, msgID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetMessageTrack 获取消息轨迹
 * 通过查询订阅该 Topic 的消费者组，逐一检查消费进度来判断消息是否已被消费
 */
export function GetMessageTrack(topic: string, msgID: string): $CancellablePromise<(model$0.MessageTrackItem | null)[]> {
    return $Call.ByID(3455367192, topic, msgID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * QueryDLQMessages 查询消费者组的死信队列消息
 */
export function QueryDLQMessages(groupName: string, maxResults: number): $CancellablePromise<(model$0.MessageItem | null)[]> {
    return $Call.ByID(1071131889, groupName, maxResults).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * QueryMessageByID 按消息 ID 查询消息
 */
export function QueryMessageByID(topic: string, msgID: string): $CancellablePromise<model$0.MessageItem | null> {
    return $Call.ByID(2698022101, topic, msgID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * QueryMessages 查询消息，startTime/endTime 为 Unix 毫秒时间戳，0 表示不限制
 */
export function QueryMessages(topic: string, key: string, maxResults: number, startTime: number, endTime: number): $CancellablePromise<(model$0.MessageItem | null)[]> {
    return $Call.ByID(1433538526, topic, key, maxResults, startTime, endTime).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * QueryRetryMessages 查询消费者组的重试队列消息
 */
export function QueryRetryMessages(groupName: string, maxResults: number): $CancellablePromise<(model$0.MessageItem | null)[]> {
    return $Call.ByID(2529028236, groupName, maxResults).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ResendMessage 重投消息
 */
export function ResendMessage(consumerGroup: string, clientID: string, topic: string, msgID: string): $CancellablePromise<string> {
    return $Call.ByID(1358375348, consumerGroup, clientID, topic, msgID);
}

/**
 * SendMessage ��送消息到指定 Topic
 */
export function SendMessage(topic: string, tags: string, keys: string, body: string): $CancellablePromise<string> {
    return $Call.ByID(1221390803, topic, tags, keys, body);
}

// Private type creation functions
const $$createType0 = model$0.MessageItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.MessageTrackItem.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($$createType1);
