// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MessageService 消息查询服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * GetMessageDetail 获取消息详情
 */
export function GetMessageDetail(topic: string, msgID: string): $CancellablePromise<model$0.MessageItem | null> {
    return $Call.ByID(826218736, topic, msgID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetMessageTrack 获取消息轨迹
 * 注意：rocketmq-admin-go 库当前版本暂不支持 MessageTrackDetail
 */
export function GetMessageTrack(topic: string, msgID: string): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(3455367192, topic, msgID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * QueryMessageByID 按消息 ID 查询消息
 */
export function QueryMessageByID(topic: string, msgID: string): $CancellablePromise<model$0.MessageItem | null> {
    return $Call.ByID(2698022101, topic, msgID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * QueryMessages 查询消息
 */
export function QueryMessages(topic: string, key: string, maxResults: number): $CancellablePromise<(model$0.MessageItem | null)[]> {
    return $Call.ByID(1433538526, topic, key, maxResults).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ResendMessage 重投消息
 */
export function ResendMessage(consumerGroup: string, clientID: string, topic: string, msgID: string): $CancellablePromise<string> {
    return $Call.ByID(1358375348, consumerGroup, clientID, topic, msgID);
}

// Private type creation functions
const $$createType0 = model$0.MessageItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType1);
