// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MessageService 消息查询服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * GetMessageDetail 获取消息详情
 * @param {string} topic
 * @param {string} msgID
 * @returns {$CancellablePromise<model$0.MessageItem | null>}
 */
export function GetMessageDetail(topic, msgID) {
    return $Call.ByID(826218736, topic, msgID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetMessageTrack 获取消息轨迹
 * 通过查询订阅该 Topic 的消费者组，逐一检查消费进度来判断消息是否已被消费
 * @param {string} topic
 * @param {string} msgID
 * @returns {$CancellablePromise<(model$0.MessageTrackItem | null)[]>}
 */
export function GetMessageTrack(topic, msgID) {
    return $Call.ByID(3455367192, topic, msgID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * QueryMessageByID 按消息 ID 查询消息
 * @param {string} topic
 * @param {string} msgID
 * @returns {$CancellablePromise<model$0.MessageItem | null>}
 */
export function QueryMessageByID(topic, msgID) {
    return $Call.ByID(2698022101, topic, msgID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * QueryMessages 查询消息，startTime/endTime 为 Unix 毫秒时间戳，0 表示不限制
 * @param {string} topic
 * @param {string} key
 * @param {number} maxResults
 * @param {number} startTime
 * @param {number} endTime
 * @returns {$CancellablePromise<(model$0.MessageItem | null)[]>}
 */
export function QueryMessages(topic, key, maxResults, startTime, endTime) {
    return $Call.ByID(1433538526, topic, key, maxResults, startTime, endTime).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ResendMessage 重投消息
 * @param {string} consumerGroup
 * @param {string} clientID
 * @param {string} topic
 * @param {string} msgID
 * @returns {$CancellablePromise<string>}
 */
export function ResendMessage(consumerGroup, clientID, topic, msgID) {
    return $Call.ByID(1358375348, consumerGroup, clientID, topic, msgID);
}

/**
 * SendMessage 发送消息到指定 Topic
 * @param {string} topic
 * @param {string} tags
 * @param {string} keys
 * @param {string} body
 * @returns {$CancellablePromise<string>}
 */
export function SendMessage(topic, tags, keys, body) {
    return $Call.ByID(1221390803, topic, tags, keys, body);
}

// Private type creation functions
const $$createType0 = model$0.MessageItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.MessageTrackItem.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($$createType1);
