// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 设置管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * GetSettings 获取全部设置
 */
export function GetSettings(): $CancellablePromise<model$0.AppSettings | null> {
    return $Call.ByID(2095924521).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResetSettings 重置为默认设置
 */
export function ResetSettings(): $CancellablePromise<model$0.AppSettings | null> {
    return $Call.ByID(1871038266).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateSettings 更新全部设置并持久化
 */
export function UpdateSettings(settings: model$0.AppSettings): $CancellablePromise<model$0.AppSettings | null> {
    return $Call.ByID(2966236708, settings).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.AppSettings.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
