// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 设置管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * ClearCache 清理缓存（重置临时数据）
 * @returns {$CancellablePromise<void>}
 */
export function ClearCache() {
    return $Call.ByID(935887909);
}

/**
 * ExportAllConfig 导出全部配置（设置 + 连接）为 JSON 字符串
 * @returns {$CancellablePromise<string>}
 */
export function ExportAllConfig() {
    return $Call.ByID(3919737823);
}

/**
 * GetAutoConnectLast 获取是否自动连接上次集群
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoConnectLast() {
    return $Call.ByID(2710643303);
}

/**
 * GetConnectTimeout 获取连接超时时间
 * @returns {$CancellablePromise<time$0.Duration>}
 */
export function GetConnectTimeout() {
    return $Call.ByID(2956504717);
}

/**
 * GetFetchLimit 获取单页拉取数量
 * @returns {$CancellablePromise<number>}
 */
export function GetFetchLimit() {
    return $Call.ByID(3477379839);
}

/**
 * GetRequestTimeout 获取请求超时时间
 * @returns {$CancellablePromise<time$0.Duration>}
 */
export function GetRequestTimeout() {
    return $Call.ByID(174043552);
}

/**
 * GetSettings 获取全部设置
 * @returns {$CancellablePromise<model$0.AppSettings | null>}
 */
export function GetSettings() {
    return $Call.ByID(2095924521).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ImportAllConfig 导入全部配置
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function ImportAllConfig(jsonStr) {
    return $Call.ByID(3033237922, jsonStr);
}

/**
 * ResetSettings 重置为默认设置
 * @returns {$CancellablePromise<model$0.AppSettings | null>}
 */
export function ResetSettings() {
    return $Call.ByID(1871038266).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * UpdateSettings 更新全部设置并持久化
 * @param {model$0.AppSettings} settings
 * @returns {$CancellablePromise<model$0.AppSettings | null>}
 */
export function UpdateSettings(settings) {
    return $Call.ByID(2966236708, settings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = model$0.AppSettings.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
