// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TopicService Topic 管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * CreateTopic 创建 Topic
 * @param {string} topic
 * @param {string} brokerAddr
 * @param {number} readQueue
 * @param {number} writeQueue
 * @param {string} perm
 * @returns {$CancellablePromise<void>}
 */
export function CreateTopic(topic, brokerAddr, readQueue, writeQueue, perm) {
    return $Call.ByID(987344489, topic, brokerAddr, readQueue, writeQueue, perm);
}

/**
 * DeleteTopic 删除 Topic
 * @param {string} topic
 * @param {string} clusterName
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTopic(topic, clusterName) {
    return $Call.ByID(715399012, topic, clusterName);
}

/**
 * GetTopicDetail 获取 Topic 详情
 * @param {string} topicName
 * @returns {$CancellablePromise<model$0.TopicItem | null>}
 */
export function GetTopicDetail(topicName) {
    return $Call.ByID(2035716144, topicName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetTopicRoute 获取 Topic 路由信息
 * @param {string} topicName
 * @returns {$CancellablePromise<model$0.TopicRouteItem[]>}
 */
export function GetTopicRoute(topicName) {
    return $Call.ByID(72765298, topicName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetTopicStats 获取 Topic 统计信息
 * @param {string} topic
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetTopicStats(topic) {
    return $Call.ByID(3741851472, topic).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetTopicTotal 获取 Topic 总数（排除系统 Topic）
 * @returns {$CancellablePromise<number>}
 */
export function GetTopicTotal() {
    return $Call.ByID(3763386193);
}

/**
 * GetTopics 获取所有 Topic 列表
 * @returns {$CancellablePromise<(model$0.TopicItem | null)[]>}
 */
export function GetTopics() {
    return $Call.ByID(2552409270).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetTopicsByCluster 按集群获取 Topic 列表
 * @param {string} clusterName
 * @returns {$CancellablePromise<(model$0.TopicItem | null)[]>}
 */
export function GetTopicsByCluster(clusterName) {
    return $Call.ByID(3041396751, clusterName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * UpdateTopic 更新 Topic 配置
 * @param {string} topic
 * @param {string} brokerAddr
 * @param {number} readQueue
 * @param {number} writeQueue
 * @param {string} perm
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTopic(topic, brokerAddr, readQueue, writeQueue, perm) {
    return $Call.ByID(2345273134, topic, brokerAddr, readQueue, writeQueue, perm);
}

// Private type creation functions
const $$createType0 = model$0.TopicItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.TopicRouteItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Array($$createType1);
