// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TopicService Topic 管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * CreateTopic 创建 Topic
 */
export function CreateTopic(topic: string, brokerAddr: string, readQueue: number, writeQueue: number, perm: string): $CancellablePromise<void> {
    return $Call.ByID(987344489, topic, brokerAddr, readQueue, writeQueue, perm);
}

/**
 * DeleteTopic 删除 Topic
 */
export function DeleteTopic(topic: string, clusterName: string): $CancellablePromise<void> {
    return $Call.ByID(715399012, topic, clusterName);
}

/**
 * GetTopicDetail 获取 Topic 详情
 */
export function GetTopicDetail(topicName: string): $CancellablePromise<model$0.TopicItem | null> {
    return $Call.ByID(2035716144, topicName).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTopicRoute 获取 Topic 路由信息
 */
export function GetTopicRoute(topicName: string): $CancellablePromise<model$0.TopicRouteItem[]> {
    return $Call.ByID(72765298, topicName).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTopicStats 获取 Topic 统计信息
 */
export function GetTopicStats(topic: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3741851472, topic).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetTopicTotal 获取 Topic 总数（排除系统 Topic）
 */
export function GetTopicTotal(): $CancellablePromise<number> {
    return $Call.ByID(3763386193);
}

/**
 * GetTopics 获取所有 Topic 列表
 */
export function GetTopics(): $CancellablePromise<(model$0.TopicItem | null)[]> {
    return $Call.ByID(2552409270).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetTopicsByCluster 按集群获取 Topic 列表
 */
export function GetTopicsByCluster(clusterName: string): $CancellablePromise<(model$0.TopicItem | null)[]> {
    return $Call.ByID(3041396751, clusterName).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * UpdateTopic 更新 Topic 配置
 */
export function UpdateTopic(topic: string, brokerAddr: string, readQueue: number, writeQueue: number, perm: string): $CancellablePromise<void> {
    return $Call.ByID(2345273134, topic, brokerAddr, readQueue, writeQueue, perm);
}

// Private type creation functions
const $$createType0 = model$0.TopicItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.TopicRouteItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Array($$createType1);
