// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BrokerNode Broker 节点信息
 */
export class BrokerNode {
    /**
     * 节点ID
     */
    "id": number;

    /**
     * 所属集群
     */
    "cluster": string;

    /**
     * Broker 名称
     */
    "brokerName": string;

    /**
     * Broker ID
     */
    "brokerId": number;

    /**
     * 角色(MASTER/SLAVE)
     */
    "role": BrokerRole;

    /**
     * 主地址
     */
    "address": string;

    /**
     * HA地址
     */
    "haAddress": string;

    /**
     * 版本号
     */
    "version": string;

    /**
     * 节点状态
     */
    "status": NodeStatus;

    /**
     * Topic 数量
     */
    "topics": number;

    /**
     * 消费者组数量
     */
    "groups": number;

    /**
     * 入流 TPS
     */
    "tpsIn": number;

    /**
     * 出流 TPS
     */
    "tpsOut": number;

    /**
     * TPS 入流历史
     */
    "tpsInHistory": number[];

    /**
     * TPS 出流历史
     */
    "tpsOutHistory": number[];

    /**
     * 今日入消息量
     */
    "msgInToday": number;

    /**
     * 今日出消息量
     */
    "msgOutToday": number;

    /**
     * CommitLog 磁盘使用率
     */
    "commitLogDiskUsage": number;

    /**
     * ConsumeQueue 磁盘使用率
     */
    "consumeQueueDiskUsage": number;

    /**
     * 最后更新时间
     */
    "lastUpdate": string;

    /**
     * 备注
     */
    "remark": string;

    /** Creates a new BrokerNode instance. */
    constructor($$source: Partial<BrokerNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("brokerName" in $$source)) {
            this["brokerName"] = "";
        }
        if (!("brokerId" in $$source)) {
            this["brokerId"] = 0;
        }
        if (!("role" in $$source)) {
            this["role"] = BrokerRole.$zero;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("haAddress" in $$source)) {
            this["haAddress"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = NodeStatus.$zero;
        }
        if (!("topics" in $$source)) {
            this["topics"] = 0;
        }
        if (!("groups" in $$source)) {
            this["groups"] = 0;
        }
        if (!("tpsIn" in $$source)) {
            this["tpsIn"] = 0;
        }
        if (!("tpsOut" in $$source)) {
            this["tpsOut"] = 0;
        }
        if (!("tpsInHistory" in $$source)) {
            this["tpsInHistory"] = [];
        }
        if (!("tpsOutHistory" in $$source)) {
            this["tpsOutHistory"] = [];
        }
        if (!("msgInToday" in $$source)) {
            this["msgInToday"] = 0;
        }
        if (!("msgOutToday" in $$source)) {
            this["msgOutToday"] = 0;
        }
        if (!("commitLogDiskUsage" in $$source)) {
            this["commitLogDiskUsage"] = 0;
        }
        if (!("consumeQueueDiskUsage" in $$source)) {
            this["consumeQueueDiskUsage"] = 0;
        }
        if (!("lastUpdate" in $$source)) {
            this["lastUpdate"] = "";
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrokerNode instance from a string or object.
     */
    static createFrom($$source: any = {}): BrokerNode {
        const $$createField13_0 = $$createType0;
        const $$createField14_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tpsInHistory" in $$parsedSource) {
            $$parsedSource["tpsInHistory"] = $$createField13_0($$parsedSource["tpsInHistory"]);
        }
        if ("tpsOutHistory" in $$parsedSource) {
            $$parsedSource["tpsOutHistory"] = $$createField14_0($$parsedSource["tpsOutHistory"]);
        }
        return new BrokerNode($$parsedSource as Partial<BrokerNode>);
    }
}

/**
 * BrokerRole Broker 角色
 */
export enum BrokerRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleMaster = "MASTER",
    RoleSlave = "SLAVE",
};

/**
 * ClusterInfo 集群概览信息
 */
export class ClusterInfo {
    /**
     * 集群名称
     */
    "clusterName": string;

    /**
     * Broker 总数
     */
    "totalBrokers": number;

    /**
     * 在线 Broker 数
     */
    "onlineBrokers": number;

    /**
     * Topic 总数
     */
    "totalTopics": number;

    /**
     * 消费者组总数
     */
    "totalGroups": number;

    /**
     * 平均磁盘使用率
     */
    "avgDiskUsage": number;

    /**
     * NameServer 列表
     */
    "nameServers": string[];

    /**
     * Broker 列表
     */
    "brokers": (BrokerNode | null)[];

    /** Creates a new ClusterInfo instance. */
    constructor($$source: Partial<ClusterInfo> = {}) {
        if (!("clusterName" in $$source)) {
            this["clusterName"] = "";
        }
        if (!("totalBrokers" in $$source)) {
            this["totalBrokers"] = 0;
        }
        if (!("onlineBrokers" in $$source)) {
            this["onlineBrokers"] = 0;
        }
        if (!("totalTopics" in $$source)) {
            this["totalTopics"] = 0;
        }
        if (!("totalGroups" in $$source)) {
            this["totalGroups"] = 0;
        }
        if (!("avgDiskUsage" in $$source)) {
            this["avgDiskUsage"] = 0;
        }
        if (!("nameServers" in $$source)) {
            this["nameServers"] = [];
        }
        if (!("brokers" in $$source)) {
            this["brokers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterInfo {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nameServers" in $$parsedSource) {
            $$parsedSource["nameServers"] = $$createField6_0($$parsedSource["nameServers"]);
        }
        if ("brokers" in $$parsedSource) {
            $$parsedSource["brokers"] = $$createField7_0($$parsedSource["brokers"]);
        }
        return new ClusterInfo($$parsedSource as Partial<ClusterInfo>);
    }
}

/**
 * ClusterSummary 集群状态概览（用于前端展示）
 */
export class ClusterSummary {
    /**
     * 集群数量
     */
    "totalClusters": number;

    /**
     * Broker 总数
     */
    "totalBrokers": number;

    /**
     * 在线 Broker 数
     */
    "onlineBrokers": number;

    /**
     * 告警 Broker 数
     */
    "warningBrokers": number;

    /**
     * 离线 Broker 数
     */
    "offlineBrokers": number;

    /**
     * 平均磁盘使用率
     */
    "avgDiskUsage": number;

    /** Creates a new ClusterSummary instance. */
    constructor($$source: Partial<ClusterSummary> = {}) {
        if (!("totalClusters" in $$source)) {
            this["totalClusters"] = 0;
        }
        if (!("totalBrokers" in $$source)) {
            this["totalBrokers"] = 0;
        }
        if (!("onlineBrokers" in $$source)) {
            this["onlineBrokers"] = 0;
        }
        if (!("warningBrokers" in $$source)) {
            this["warningBrokers"] = 0;
        }
        if (!("offlineBrokers" in $$source)) {
            this["offlineBrokers"] = 0;
        }
        if (!("avgDiskUsage" in $$source)) {
            this["avgDiskUsage"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterSummary($$parsedSource as Partial<ClusterSummary>);
    }
}

/**
 * Connection 连接配置
 */
export class Connection {
    /**
     * 连接ID
     */
    "id": number;

    /**
     * 连接名称
     */
    "name": string;

    /**
     * 环境类型
     */
    "env": ConnectionEnv;

    /**
     * NameServer 地址
     */
    "nameServer": string;

    /**
     * 超时时间(秒)
     */
    "timeoutSec": number;

    /**
     * 是否启用 ACL 认证
     */
    "enableACL": boolean;

    /**
     * ACL AccessKey
     */
    "accessKey": string;

    /**
     * ACL SecretKey
     */
    "secretKey": string;

    /**
     * 连接状态
     */
    "status": ConnectionStatus;

    /**
     * 最近检测时间
     */
    "lastCheck": string;

    /**
     * 是否默认连接
     */
    "isDefault": boolean;

    /**
     * 备注
     */
    "remark": string;

    /** Creates a new Connection instance. */
    constructor($$source: Partial<Connection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("env" in $$source)) {
            this["env"] = ConnectionEnv.$zero;
        }
        if (!("nameServer" in $$source)) {
            this["nameServer"] = "";
        }
        if (!("timeoutSec" in $$source)) {
            this["timeoutSec"] = 0;
        }
        if (!("enableACL" in $$source)) {
            this["enableACL"] = false;
        }
        if (!("accessKey" in $$source)) {
            this["accessKey"] = "";
        }
        if (!("secretKey" in $$source)) {
            this["secretKey"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = ConnectionStatus.$zero;
        }
        if (!("lastCheck" in $$source)) {
            this["lastCheck"] = "";
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     */
    static createFrom($$source: any = {}): Connection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection($$parsedSource as Partial<Connection>);
    }
}

/**
 * ConnectionEnv 连接环境类型
 */
export enum ConnectionEnv {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EnvProduction = "生产",
    EnvTest = "测试",
    EnvDevelopment = "开发",
};

/**
 * ConnectionStatus 连接状态
 */
export enum ConnectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusOnline = "online",
    StatusOffline = "offline",
};

/**
 * ConsumeMode 消费模式
 */
export enum ConsumeMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModeClustering = "CLUSTERING",
    ModeBroadcasting = "BROADCASTING",
};

/**
 * ConsumerGroupItem 消费者组信息
 */
export class ConsumerGroupItem {
    /**
     * 消费者组ID
     */
    "id": number;

    /**
     * 消费者组名称
     */
    "group": string;

    /**
     * 所属集群
     */
    "cluster": string;

    /**
     * 消费模式
     */
    "consumeMode": ConsumeMode;

    /**
     * 状态
     */
    "status": GroupStatus;

    /**
     * 在线客户端数
     */
    "onlineClients": number;

    /**
     * 订阅 Topic 数
     */
    "topicCount": number;

    /**
     * 堆积量
     */
    "lag": number;

    /**
     * 重试 QPS
     */
    "retryQps": number;

    /**
     * 死信数量
     */
    "dlq": number;

    /**
     * 最大重试次数
     */
    "maxRetry": number;

    /**
     * 最后更新时间
     */
    "lastUpdate": string;

    /**
     * 备注
     */
    "remark": string;

    /**
     * 订阅关系列表
     */
    "subscriptions": GroupSubscription[];

    /**
     * 客户端列表
     */
    "clients": GroupClient[];

    /** Creates a new ConsumerGroupItem instance. */
    constructor($$source: Partial<ConsumerGroupItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("consumeMode" in $$source)) {
            this["consumeMode"] = ConsumeMode.$zero;
        }
        if (!("status" in $$source)) {
            this["status"] = GroupStatus.$zero;
        }
        if (!("onlineClients" in $$source)) {
            this["onlineClients"] = 0;
        }
        if (!("topicCount" in $$source)) {
            this["topicCount"] = 0;
        }
        if (!("lag" in $$source)) {
            this["lag"] = 0;
        }
        if (!("retryQps" in $$source)) {
            this["retryQps"] = 0;
        }
        if (!("dlq" in $$source)) {
            this["dlq"] = 0;
        }
        if (!("maxRetry" in $$source)) {
            this["maxRetry"] = 0;
        }
        if (!("lastUpdate" in $$source)) {
            this["lastUpdate"] = "";
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("subscriptions" in $$source)) {
            this["subscriptions"] = [];
        }
        if (!("clients" in $$source)) {
            this["clients"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsumerGroupItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsumerGroupItem {
        const $$createField13_0 = $$createType6;
        const $$createField14_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subscriptions" in $$parsedSource) {
            $$parsedSource["subscriptions"] = $$createField13_0($$parsedSource["subscriptions"]);
        }
        if ("clients" in $$parsedSource) {
            $$parsedSource["clients"] = $$createField14_0($$parsedSource["clients"]);
        }
        return new ConsumerGroupItem($$parsedSource as Partial<ConsumerGroupItem>);
    }
}

/**
 * GroupClient 消费者客户端信息
 */
export class GroupClient {
    /**
     * 客户端ID
     */
    "clientId": string;

    /**
     * IP 地址
     */
    "ip": string;

    /**
     * 版本号
     */
    "version": string;

    /**
     * 最后心跳时间
     */
    "lastHeartbeat": string;

    /** Creates a new GroupClient instance. */
    constructor($$source: Partial<GroupClient> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("lastHeartbeat" in $$source)) {
            this["lastHeartbeat"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupClient instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupClient {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupClient($$parsedSource as Partial<GroupClient>);
    }
}

/**
 * GroupStatus 消费者组状态
 */
export enum GroupStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    GroupOnline = "online",
    GroupWarning = "warning",
    GroupOffline = "offline",
};

/**
 * GroupSubscription 订阅关系
 */
export class GroupSubscription {
    /**
     * Topic 名称
     */
    "topic": string;

    /**
     * 过滤表达式
     */
    "expression": string;

    /**
     * 消费 TPS
     */
    "consumeTps": number;

    /** Creates a new GroupSubscription instance. */
    constructor($$source: Partial<GroupSubscription> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("expression" in $$source)) {
            this["expression"] = "";
        }
        if (!("consumeTps" in $$source)) {
            this["consumeTps"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupSubscription instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupSubscription {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupSubscription($$parsedSource as Partial<GroupSubscription>);
    }
}

/**
 * MessageItem 消息信息
 */
export class MessageItem {
    /**
     * 消息序号
     */
    "id": number;

    /**
     * 所属集群
     */
    "cluster": string;

    /**
     * Topic 名称
     */
    "topic": string;

    /**
     * 消息ID
     */
    "messageId": string;

    /**
     * 消息标签
     */
    "tags": string;

    /**
     * 消息Keys
     */
    "keys": string;

    /**
     * 生产者组
     */
    "producerGroup": string;

    /**
     * 队列ID
     */
    "queueId": number;

    /**
     * 队列偏移
     */
    "queueOffset": number;

    /**
     * 存储节点
     */
    "storeHost": string;

    /**
     * 生产节点
     */
    "bornHost": string;

    /**
     * 存储时间
     */
    "storeTime": string;

    /**
     * 存储时间戳
     */
    "storeTimestamp": number;

    /**
     * 消息状态
     */
    "status": MessageStatus;

    /**
     * 重试次数
     */
    "retryTimes": number;

    /**
     * 消息体
     */
    "body": string;

    /**
     * 消息属性
     */
    "properties": { [_ in string]?: string };

    /** Creates a new MessageItem instance. */
    constructor($$source: Partial<MessageItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = "";
        }
        if (!("keys" in $$source)) {
            this["keys"] = "";
        }
        if (!("producerGroup" in $$source)) {
            this["producerGroup"] = "";
        }
        if (!("queueId" in $$source)) {
            this["queueId"] = 0;
        }
        if (!("queueOffset" in $$source)) {
            this["queueOffset"] = 0;
        }
        if (!("storeHost" in $$source)) {
            this["storeHost"] = "";
        }
        if (!("bornHost" in $$source)) {
            this["bornHost"] = "";
        }
        if (!("storeTime" in $$source)) {
            this["storeTime"] = "";
        }
        if (!("storeTimestamp" in $$source)) {
            this["storeTimestamp"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = MessageStatus.$zero;
        }
        if (!("retryTimes" in $$source)) {
            this["retryTimes"] = 0;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("properties" in $$source)) {
            this["properties"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageItem instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageItem {
        const $$createField16_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField16_0($$parsedSource["properties"]);
        }
        return new MessageItem($$parsedSource as Partial<MessageItem>);
    }
}

/**
 * MessageStatus 消息状态
 */
export enum MessageStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MsgNormal = "normal",
    MsgRetry = "retry",
    MsgDLQ = "dlq",
};

/**
 * NameServerNode NameServer 节点信息
 */
export class NameServerNode {
    /**
     * 节点ID
     */
    "id": number;

    /**
     * 所属集群
     */
    "cluster": string;

    /**
     * 节点地址
     */
    "address": string;

    /**
     * 版本号
     */
    "version": string;

    /**
     * 节点状态
     */
    "status": NodeStatus;

    /**
     * 最后可见时间
     */
    "lastSeen": string;

    /** Creates a new NameServerNode instance. */
    constructor($$source: Partial<NameServerNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = NodeStatus.$zero;
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NameServerNode instance from a string or object.
     */
    static createFrom($$source: any = {}): NameServerNode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NameServerNode($$parsedSource as Partial<NameServerNode>);
    }
}

/**
 * NodeStatus 节点状态
 */
export enum NodeStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NodeOnline = "online",
    NodeWarning = "warning",
    NodeOffline = "offline",
};

/**
 * TopicItem Topic 信息
 */
export class TopicItem {
    /**
     * Topic ID
     */
    "id": number;

    /**
     * Topic 名称
     */
    "topic": string;

    /**
     * 所属集群
     */
    "cluster": string;

    /**
     * 读队列数
     */
    "readQueue": number;

    /**
     * 写队列数
     */
    "writeQueue": number;

    /**
     * 权限
     */
    "perm": TopicPerm;

    /**
     * 消息类型
     */
    "messageType": TopicMessageType;

    /**
     * 消费者组数量
     */
    "consumerGroups": number;

    /**
     * 入流 TPS
     */
    "tpsIn": number;

    /**
     * 出流 TPS
     */
    "tpsOut": number;

    /**
     * 最后更新时间
     */
    "lastUpdated": string;

    /**
     * 描述
     */
    "description": string;

    /**
     * 路由信息
     */
    "routes": TopicRouteItem[];

    /** Creates a new TopicItem instance. */
    constructor($$source: Partial<TopicItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("readQueue" in $$source)) {
            this["readQueue"] = 0;
        }
        if (!("writeQueue" in $$source)) {
            this["writeQueue"] = 0;
        }
        if (!("perm" in $$source)) {
            this["perm"] = TopicPerm.$zero;
        }
        if (!("messageType" in $$source)) {
            this["messageType"] = TopicMessageType.$zero;
        }
        if (!("consumerGroups" in $$source)) {
            this["consumerGroups"] = 0;
        }
        if (!("tpsIn" in $$source)) {
            this["tpsIn"] = 0;
        }
        if (!("tpsOut" in $$source)) {
            this["tpsOut"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            this["lastUpdated"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("routes" in $$source)) {
            this["routes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TopicItem {
        const $$createField12_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("routes" in $$parsedSource) {
            $$parsedSource["routes"] = $$createField12_0($$parsedSource["routes"]);
        }
        return new TopicItem($$parsedSource as Partial<TopicItem>);
    }
}

/**
 * TopicMessageType 消息类型
 */
export enum TopicMessageType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MessageTypeNormal = "Normal",
    MessageTypeFIFO = "FIFO",
    MessageTypeDelay = "Delay",
};

/**
 * TopicPerm Topic 权限
 */
export enum TopicPerm {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermRW = "RW",
    PermR = "R",
    PermW = "W",
    PermDeny = "DENY",
};

/**
 * TopicRouteItem Topic 路由条目
 */
export class TopicRouteItem {
    /**
     * Broker 名称
     */
    "broker": string;

    /**
     * Broker 地址
     */
    "brokerAddr": string;

    /**
     * 读队列数
     */
    "readQueue": number;

    /**
     * 写队列数
     */
    "writeQueue": number;

    /**
     * 权限
     */
    "perm": TopicPerm;

    /** Creates a new TopicRouteItem instance. */
    constructor($$source: Partial<TopicRouteItem> = {}) {
        if (!("broker" in $$source)) {
            this["broker"] = "";
        }
        if (!("brokerAddr" in $$source)) {
            this["brokerAddr"] = "";
        }
        if (!("readQueue" in $$source)) {
            this["readQueue"] = 0;
        }
        if (!("writeQueue" in $$source)) {
            this["writeQueue"] = 0;
        }
        if (!("perm" in $$source)) {
            this["perm"] = TopicPerm.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicRouteItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TopicRouteItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopicRouteItem($$parsedSource as Partial<TopicRouteItem>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = BrokerNode.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = GroupSubscription.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = GroupClient.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = TopicRouteItem.createFrom;
const $$createType11 = $Create.Array($$createType10);
