// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings 应用设置
 */
export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("language" in $$source)) {
            /**
             * 通用设置
             * 语言: "en" | "zh"
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("fontSize" in $$source)) {
            /**
             * 字体大小: "small" | "medium" | "large"
             * @member
             * @type {string}
             */
            this["fontSize"] = "";
        }
        if (!("monospaceFont" in $$source)) {
            /**
             * 等宽字体
             * @member
             * @type {string}
             */
            this["monospaceFont"] = "";
        }
        if (!("autoConnectLast" in $$source)) {
            /**
             * 启动时自动连接上次集群
             * @member
             * @type {boolean}
             */
            this["autoConnectLast"] = false;
        }
        if (!("connectTimeoutMs" in $$source)) {
            /**
             * 连接与网络
             * 连接超时(ms)
             * @member
             * @type {number}
             */
            this["connectTimeoutMs"] = 0;
        }
        if (!("requestTimeoutMs" in $$source)) {
            /**
             * 请求超时(ms)
             * @member
             * @type {number}
             */
            this["requestTimeoutMs"] = 0;
        }
        if (!("globalAccessKey" in $$source)) {
            /**
             * 默认 AccessKey
             * @member
             * @type {string}
             */
            this["globalAccessKey"] = "";
        }
        if (!("globalSecretKey" in $$source)) {
            /**
             * 默认 SecretKey
             * @member
             * @type {string}
             */
            this["globalSecretKey"] = "";
        }
        if (!("skipTlsVerify" in $$source)) {
            /**
             * 跳过 TLS 校验
             * @member
             * @type {boolean}
             */
            this["skipTlsVerify"] = false;
        }
        if (!("proxyEnabled" in $$source)) {
            /**
             * 启用代理
             * @member
             * @type {boolean}
             */
            this["proxyEnabled"] = false;
        }
        if (!("proxyType" in $$source)) {
            /**
             * 代理类型: "http" | "socks5"
             * @member
             * @type {string}
             */
            this["proxyType"] = "";
        }
        if (!("proxyHost" in $$source)) {
            /**
             * 代理地址
             * @member
             * @type {string}
             */
            this["proxyHost"] = "";
        }
        if (!("proxyPort" in $$source)) {
            /**
             * 代理端口
             * @member
             * @type {string}
             */
            this["proxyPort"] = "";
        }
        if (!("timezone" in $$source)) {
            /**
             * 消息与显示
             * 时区: "local" | "utc"
             * @member
             * @type {string}
             */
            this["timezone"] = "";
        }
        if (!("timestampFormat" in $$source)) {
            /**
             * 时间戳格式: "datetime" | "ms"
             * @member
             * @type {string}
             */
            this["timestampFormat"] = "";
        }
        if (!("autoFormatJson" in $$source)) {
            /**
             * JSON 自动格式化
             * @member
             * @type {boolean}
             */
            this["autoFormatJson"] = false;
        }
        if (!("maxPayloadRenderBytes" in $$source)) {
            /**
             * 消息截断阈值(字节)
             * @member
             * @type {number}
             */
            this["maxPayloadRenderBytes"] = 0;
        }
        if (!("fetchLimit" in $$source)) {
            /**
             * 单页拉取数量
             * @member
             * @type {number}
             */
            this["fetchLimit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

/**
 * BrokerNode Broker 节点信息
 */
export class BrokerNode {
    /**
     * Creates a new BrokerNode instance.
     * @param {Partial<BrokerNode>} [$$source = {}] - The source object to create the BrokerNode.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 节点ID
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("cluster" in $$source)) {
            /**
             * 所属集群
             * @member
             * @type {string}
             */
            this["cluster"] = "";
        }
        if (!("brokerName" in $$source)) {
            /**
             * Broker 名称
             * @member
             * @type {string}
             */
            this["brokerName"] = "";
        }
        if (!("brokerId" in $$source)) {
            /**
             * Broker ID
             * @member
             * @type {number}
             */
            this["brokerId"] = 0;
        }
        if (!("role" in $$source)) {
            /**
             * 角色(MASTER/SLAVE)
             * @member
             * @type {BrokerRole}
             */
            this["role"] = BrokerRole.$zero;
        }
        if (!("address" in $$source)) {
            /**
             * 主地址
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("haAddress" in $$source)) {
            /**
             * HA地址
             * @member
             * @type {string}
             */
            this["haAddress"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * 版本号
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * 节点状态
             * @member
             * @type {NodeStatus}
             */
            this["status"] = NodeStatus.$zero;
        }
        if (!("topics" in $$source)) {
            /**
             * Topic 数量
             * @member
             * @type {number}
             */
            this["topics"] = 0;
        }
        if (!("groups" in $$source)) {
            /**
             * 消费者组数量
             * @member
             * @type {number}
             */
            this["groups"] = 0;
        }
        if (!("tpsIn" in $$source)) {
            /**
             * 入流 TPS
             * @member
             * @type {number}
             */
            this["tpsIn"] = 0;
        }
        if (!("tpsOut" in $$source)) {
            /**
             * 出流 TPS
             * @member
             * @type {number}
             */
            this["tpsOut"] = 0;
        }
        if (!("tpsInHistory" in $$source)) {
            /**
             * TPS 入流历史
             * @member
             * @type {number[]}
             */
            this["tpsInHistory"] = [];
        }
        if (!("tpsOutHistory" in $$source)) {
            /**
             * TPS 出流历史
             * @member
             * @type {number[]}
             */
            this["tpsOutHistory"] = [];
        }
        if (!("msgInToday" in $$source)) {
            /**
             * 今日入消息量
             * @member
             * @type {number}
             */
            this["msgInToday"] = 0;
        }
        if (!("msgOutToday" in $$source)) {
            /**
             * 今日出消息量
             * @member
             * @type {number}
             */
            this["msgOutToday"] = 0;
        }
        if (!("commitLogDiskUsage" in $$source)) {
            /**
             * CommitLog 磁盘使用率
             * @member
             * @type {number}
             */
            this["commitLogDiskUsage"] = 0;
        }
        if (!("consumeQueueDiskUsage" in $$source)) {
            /**
             * ConsumeQueue 磁盘使用率
             * @member
             * @type {number}
             */
            this["consumeQueueDiskUsage"] = 0;
        }
        if (!("lastUpdate" in $$source)) {
            /**
             * 最后更新时间
             * @member
             * @type {string}
             */
            this["lastUpdate"] = "";
        }
        if (!("remark" in $$source)) {
            /**
             * 备注
             * @member
             * @type {string}
             */
            this["remark"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrokerNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BrokerNode}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType0;
        const $$createField14_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tpsInHistory" in $$parsedSource) {
            $$parsedSource["tpsInHistory"] = $$createField13_0($$parsedSource["tpsInHistory"]);
        }
        if ("tpsOutHistory" in $$parsedSource) {
            $$parsedSource["tpsOutHistory"] = $$createField14_0($$parsedSource["tpsOutHistory"]);
        }
        return new BrokerNode(/** @type {Partial<BrokerNode>} */($$parsedSource));
    }
}

/**
 * BrokerRole Broker 角色
 * @readonly
 * @enum {string}
 */
export const BrokerRole = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RoleMaster: "MASTER",
    RoleSlave: "SLAVE",
};

/**
 * ClusterInfo 集群概览信息
 */
export class ClusterInfo {
    /**
     * Creates a new ClusterInfo instance.
     * @param {Partial<ClusterInfo>} [$$source = {}] - The source object to create the ClusterInfo.
     */
    constructor($$source = {}) {
        if (!("clusterName" in $$source)) {
            /**
             * 集群名称
             * @member
             * @type {string}
             */
            this["clusterName"] = "";
        }
        if (!("totalBrokers" in $$source)) {
            /**
             * Broker 总数
             * @member
             * @type {number}
             */
            this["totalBrokers"] = 0;
        }
        if (!("onlineBrokers" in $$source)) {
            /**
             * 在线 Broker 数
             * @member
             * @type {number}
             */
            this["onlineBrokers"] = 0;
        }
        if (!("totalTopics" in $$source)) {
            /**
             * Topic 总数
             * @member
             * @type {number}
             */
            this["totalTopics"] = 0;
        }
        if (!("totalGroups" in $$source)) {
            /**
             * 消费者组总数
             * @member
             * @type {number}
             */
            this["totalGroups"] = 0;
        }
        if (!("avgDiskUsage" in $$source)) {
            /**
             * 平均磁盘使用率
             * @member
             * @type {number}
             */
            this["avgDiskUsage"] = 0;
        }
        if (!("nameServers" in $$source)) {
            /**
             * NameServer 列表
             * @member
             * @type {string[]}
             */
            this["nameServers"] = [];
        }
        if (!("brokers" in $$source)) {
            /**
             * Broker 列表
             * @member
             * @type {(BrokerNode | null)[]}
             */
            this["brokers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClusterInfo}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nameServers" in $$parsedSource) {
            $$parsedSource["nameServers"] = $$createField6_0($$parsedSource["nameServers"]);
        }
        if ("brokers" in $$parsedSource) {
            $$parsedSource["brokers"] = $$createField7_0($$parsedSource["brokers"]);
        }
        return new ClusterInfo(/** @type {Partial<ClusterInfo>} */($$parsedSource));
    }
}

/**
 * ClusterSummary 集群状态概览（用于前端展示）
 */
export class ClusterSummary {
    /**
     * Creates a new ClusterSummary instance.
     * @param {Partial<ClusterSummary>} [$$source = {}] - The source object to create the ClusterSummary.
     */
    constructor($$source = {}) {
        if (!("totalClusters" in $$source)) {
            /**
             * 集群数量
             * @member
             * @type {number}
             */
            this["totalClusters"] = 0;
        }
        if (!("totalBrokers" in $$source)) {
            /**
             * Broker 总数
             * @member
             * @type {number}
             */
            this["totalBrokers"] = 0;
        }
        if (!("onlineBrokers" in $$source)) {
            /**
             * 在线 Broker 数
             * @member
             * @type {number}
             */
            this["onlineBrokers"] = 0;
        }
        if (!("warningBrokers" in $$source)) {
            /**
             * 告警 Broker 数
             * @member
             * @type {number}
             */
            this["warningBrokers"] = 0;
        }
        if (!("offlineBrokers" in $$source)) {
            /**
             * 离线 Broker 数
             * @member
             * @type {number}
             */
            this["offlineBrokers"] = 0;
        }
        if (!("avgDiskUsage" in $$source)) {
            /**
             * 平均磁盘使用率
             * @member
             * @type {number}
             */
            this["avgDiskUsage"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClusterSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterSummary(/** @type {Partial<ClusterSummary>} */($$parsedSource));
    }
}

/**
 * Connection 连接配置
 */
export class Connection {
    /**
     * Creates a new Connection instance.
     * @param {Partial<Connection>} [$$source = {}] - The source object to create the Connection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 连接ID
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * 连接名称
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("env" in $$source)) {
            /**
             * 环境类型
             * @member
             * @type {ConnectionEnv}
             */
            this["env"] = ConnectionEnv.$zero;
        }
        if (!("nameServer" in $$source)) {
            /**
             * NameServer 地址
             * @member
             * @type {string}
             */
            this["nameServer"] = "";
        }
        if (!("timeoutSec" in $$source)) {
            /**
             * 超时时间(秒)
             * @member
             * @type {number}
             */
            this["timeoutSec"] = 0;
        }
        if (!("enableACL" in $$source)) {
            /**
             * 是否启用 ACL 认证
             * @member
             * @type {boolean}
             */
            this["enableACL"] = false;
        }
        if (!("accessKey" in $$source)) {
            /**
             * ACL AccessKey
             * @member
             * @type {string}
             */
            this["accessKey"] = "";
        }
        if (!("secretKey" in $$source)) {
            /**
             * ACL SecretKey
             * @member
             * @type {string}
             */
            this["secretKey"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * 连接状态
             * @member
             * @type {ConnectionStatus}
             */
            this["status"] = ConnectionStatus.$zero;
        }
        if (!("lastCheck" in $$source)) {
            /**
             * 最近检测时间
             * @member
             * @type {string}
             */
            this["lastCheck"] = "";
        }
        if (!("isDefault" in $$source)) {
            /**
             * 是否默认连接
             * @member
             * @type {boolean}
             */
            this["isDefault"] = false;
        }
        if (!("remark" in $$source)) {
            /**
             * 备注
             * @member
             * @type {string}
             */
            this["remark"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Connection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection(/** @type {Partial<Connection>} */($$parsedSource));
    }
}

/**
 * ConnectionEnv 连接环境类型
 * @readonly
 * @enum {string}
 */
export const ConnectionEnv = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    EnvProduction: "生产",
    EnvTest: "测试",
    EnvDevelopment: "开发",
};

/**
 * ConnectionStatus 连接状态
 * @readonly
 * @enum {string}
 */
export const ConnectionStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusOnline: "online",
    StatusOffline: "offline",
};

/**
 * ConsumeMode 消费模式
 * @readonly
 * @enum {string}
 */
export const ConsumeMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ModeClustering: "CLUSTERING",
    ModeBroadcasting: "BROADCASTING",
};

/**
 * ConsumerGroupItem 消费者组信息
 */
export class ConsumerGroupItem {
    /**
     * Creates a new ConsumerGroupItem instance.
     * @param {Partial<ConsumerGroupItem>} [$$source = {}] - The source object to create the ConsumerGroupItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 消费者组ID
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("group" in $$source)) {
            /**
             * 消费者组名称
             * @member
             * @type {string}
             */
            this["group"] = "";
        }
        if (!("cluster" in $$source)) {
            /**
             * 所属集群
             * @member
             * @type {string}
             */
            this["cluster"] = "";
        }
        if (!("consumeMode" in $$source)) {
            /**
             * 消费模式
             * @member
             * @type {ConsumeMode}
             */
            this["consumeMode"] = ConsumeMode.$zero;
        }
        if (!("status" in $$source)) {
            /**
             * 状态
             * @member
             * @type {GroupStatus}
             */
            this["status"] = GroupStatus.$zero;
        }
        if (!("onlineClients" in $$source)) {
            /**
             * 在线客户端数
             * @member
             * @type {number}
             */
            this["onlineClients"] = 0;
        }
        if (!("topicCount" in $$source)) {
            /**
             * 订阅 Topic 数
             * @member
             * @type {number}
             */
            this["topicCount"] = 0;
        }
        if (!("lag" in $$source)) {
            /**
             * 堆积量
             * @member
             * @type {number}
             */
            this["lag"] = 0;
        }
        if (!("retryQps" in $$source)) {
            /**
             * 重试 QPS
             * @member
             * @type {number}
             */
            this["retryQps"] = 0;
        }
        if (!("dlq" in $$source)) {
            /**
             * 死信数量
             * @member
             * @type {number}
             */
            this["dlq"] = 0;
        }
        if (!("maxRetry" in $$source)) {
            /**
             * 最大重试次数
             * @member
             * @type {number}
             */
            this["maxRetry"] = 0;
        }
        if (!("lastUpdate" in $$source)) {
            /**
             * 最后更新时间
             * @member
             * @type {string}
             */
            this["lastUpdate"] = "";
        }
        if (!("remark" in $$source)) {
            /**
             * 备注
             * @member
             * @type {string}
             */
            this["remark"] = "";
        }
        if (!("subscriptions" in $$source)) {
            /**
             * 订阅关系列表
             * @member
             * @type {GroupSubscription[]}
             */
            this["subscriptions"] = [];
        }
        if (!("clients" in $$source)) {
            /**
             * 客户端列表
             * @member
             * @type {GroupClient[]}
             */
            this["clients"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsumerGroupItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConsumerGroupItem}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType6;
        const $$createField14_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subscriptions" in $$parsedSource) {
            $$parsedSource["subscriptions"] = $$createField13_0($$parsedSource["subscriptions"]);
        }
        if ("clients" in $$parsedSource) {
            $$parsedSource["clients"] = $$createField14_0($$parsedSource["clients"]);
        }
        return new ConsumerGroupItem(/** @type {Partial<ConsumerGroupItem>} */($$parsedSource));
    }
}

/**
 * GroupClient 消费者客户端信息
 */
export class GroupClient {
    /**
     * Creates a new GroupClient instance.
     * @param {Partial<GroupClient>} [$$source = {}] - The source object to create the GroupClient.
     */
    constructor($$source = {}) {
        if (!("clientId" in $$source)) {
            /**
             * 客户端ID
             * @member
             * @type {string}
             */
            this["clientId"] = "";
        }
        if (!("ip" in $$source)) {
            /**
             * IP 地址
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * 版本号
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("lastHeartbeat" in $$source)) {
            /**
             * 最后心跳时间
             * @member
             * @type {string}
             */
            this["lastHeartbeat"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupClient instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GroupClient}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupClient(/** @type {Partial<GroupClient>} */($$parsedSource));
    }
}

/**
 * GroupStatus 消费者组状态
 * @readonly
 * @enum {string}
 */
export const GroupStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    GroupOnline: "online",
    GroupWarning: "warning",
    GroupOffline: "offline",
};

/**
 * GroupSubscription 订阅关系
 */
export class GroupSubscription {
    /**
     * Creates a new GroupSubscription instance.
     * @param {Partial<GroupSubscription>} [$$source = {}] - The source object to create the GroupSubscription.
     */
    constructor($$source = {}) {
        if (!("topic" in $$source)) {
            /**
             * Topic 名称
             * @member
             * @type {string}
             */
            this["topic"] = "";
        }
        if (!("expression" in $$source)) {
            /**
             * 过滤表达式
             * @member
             * @type {string}
             */
            this["expression"] = "";
        }
        if (!("consumeTps" in $$source)) {
            /**
             * 消费 TPS
             * @member
             * @type {number}
             */
            this["consumeTps"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupSubscription instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GroupSubscription}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupSubscription(/** @type {Partial<GroupSubscription>} */($$parsedSource));
    }
}

/**
 * MessageItem 消息信息
 */
export class MessageItem {
    /**
     * Creates a new MessageItem instance.
     * @param {Partial<MessageItem>} [$$source = {}] - The source object to create the MessageItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 消息序号
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("cluster" in $$source)) {
            /**
             * 所属集群
             * @member
             * @type {string}
             */
            this["cluster"] = "";
        }
        if (!("topic" in $$source)) {
            /**
             * Topic 名称
             * @member
             * @type {string}
             */
            this["topic"] = "";
        }
        if (!("messageId" in $$source)) {
            /**
             * 消息ID
             * @member
             * @type {string}
             */
            this["messageId"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * 消息标签
             * @member
             * @type {string}
             */
            this["tags"] = "";
        }
        if (!("keys" in $$source)) {
            /**
             * 消息Keys
             * @member
             * @type {string}
             */
            this["keys"] = "";
        }
        if (!("producerGroup" in $$source)) {
            /**
             * 生产者组
             * @member
             * @type {string}
             */
            this["producerGroup"] = "";
        }
        if (!("queueId" in $$source)) {
            /**
             * 队列ID
             * @member
             * @type {number}
             */
            this["queueId"] = 0;
        }
        if (!("queueOffset" in $$source)) {
            /**
             * 队列偏移
             * @member
             * @type {number}
             */
            this["queueOffset"] = 0;
        }
        if (!("storeHost" in $$source)) {
            /**
             * 存储节点
             * @member
             * @type {string}
             */
            this["storeHost"] = "";
        }
        if (!("bornHost" in $$source)) {
            /**
             * 生产节点
             * @member
             * @type {string}
             */
            this["bornHost"] = "";
        }
        if (!("storeTime" in $$source)) {
            /**
             * 存储时间
             * @member
             * @type {string}
             */
            this["storeTime"] = "";
        }
        if (!("storeTimestamp" in $$source)) {
            /**
             * 存储时间戳
             * @member
             * @type {number}
             */
            this["storeTimestamp"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * 消息状态
             * @member
             * @type {MessageStatus}
             */
            this["status"] = MessageStatus.$zero;
        }
        if (!("retryTimes" in $$source)) {
            /**
             * 重试次数
             * @member
             * @type {number}
             */
            this["retryTimes"] = 0;
        }
        if (!("body" in $$source)) {
            /**
             * 消息体
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("properties" in $$source)) {
            /**
             * 消息属性
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["properties"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageItem}
     */
    static createFrom($$source = {}) {
        const $$createField16_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField16_0($$parsedSource["properties"]);
        }
        return new MessageItem(/** @type {Partial<MessageItem>} */($$parsedSource));
    }
}

/**
 * MessageStatus 消息状态
 * @readonly
 * @enum {string}
 */
export const MessageStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MsgNormal: "normal",
    MsgRetry: "retry",
    MsgDLQ: "dlq",
};

/**
 * MessageTrackItem 消息轨迹
 */
export class MessageTrackItem {
    /**
     * Creates a new MessageTrackItem instance.
     * @param {Partial<MessageTrackItem>} [$$source = {}] - The source object to create the MessageTrackItem.
     */
    constructor($$source = {}) {
        if (!("consumerGroup" in $$source)) {
            /**
             * 消费者组
             * @member
             * @type {string}
             */
            this["consumerGroup"] = "";
        }
        if (!("trackType" in $$source)) {
            /**
             * 轨迹类型: CONSUMED / NOT_CONSUME_YET / CONSUMED_BUT_FILTERED / UNKNOWN
             * @member
             * @type {string}
             */
            this["trackType"] = "";
        }
        if (!("consumeStatus" in $$source)) {
            /**
             * 消费状态描述
             * @member
             * @type {string}
             */
            this["consumeStatus"] = "";
        }
        if (!("exceptionDesc" in $$source)) {
            /**
             * 异常描述
             * @member
             * @type {string}
             */
            this["exceptionDesc"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageTrackItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageTrackItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageTrackItem(/** @type {Partial<MessageTrackItem>} */($$parsedSource));
    }
}

/**
 * NameServerNode NameServer 节点信息
 */
export class NameServerNode {
    /**
     * Creates a new NameServerNode instance.
     * @param {Partial<NameServerNode>} [$$source = {}] - The source object to create the NameServerNode.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 节点ID
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("cluster" in $$source)) {
            /**
             * 所属集群
             * @member
             * @type {string}
             */
            this["cluster"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * 节点地址
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * 版本号
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * 节点状态
             * @member
             * @type {NodeStatus}
             */
            this["status"] = NodeStatus.$zero;
        }
        if (!("lastSeen" in $$source)) {
            /**
             * 最后可见时间
             * @member
             * @type {string}
             */
            this["lastSeen"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NameServerNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NameServerNode}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NameServerNode(/** @type {Partial<NameServerNode>} */($$parsedSource));
    }
}

/**
 * NodeStatus 节点状态
 * @readonly
 * @enum {string}
 */
export const NodeStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    NodeOnline: "online",
    NodeWarning: "warning",
    NodeOffline: "offline",
};

/**
 * TopicItem Topic 信息
 */
export class TopicItem {
    /**
     * Creates a new TopicItem instance.
     * @param {Partial<TopicItem>} [$$source = {}] - The source object to create the TopicItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * Topic ID
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("topic" in $$source)) {
            /**
             * Topic 名称
             * @member
             * @type {string}
             */
            this["topic"] = "";
        }
        if (!("cluster" in $$source)) {
            /**
             * 所属集群
             * @member
             * @type {string}
             */
            this["cluster"] = "";
        }
        if (!("readQueue" in $$source)) {
            /**
             * 读队列数
             * @member
             * @type {number}
             */
            this["readQueue"] = 0;
        }
        if (!("writeQueue" in $$source)) {
            /**
             * 写队列数
             * @member
             * @type {number}
             */
            this["writeQueue"] = 0;
        }
        if (!("perm" in $$source)) {
            /**
             * 权限
             * @member
             * @type {TopicPerm}
             */
            this["perm"] = TopicPerm.$zero;
        }
        if (!("messageType" in $$source)) {
            /**
             * 消息类型
             * @member
             * @type {TopicMessageType}
             */
            this["messageType"] = TopicMessageType.$zero;
        }
        if (!("consumerGroups" in $$source)) {
            /**
             * 消费者组数量
             * @member
             * @type {number}
             */
            this["consumerGroups"] = 0;
        }
        if (!("tpsIn" in $$source)) {
            /**
             * 入流 TPS
             * @member
             * @type {number}
             */
            this["tpsIn"] = 0;
        }
        if (!("tpsOut" in $$source)) {
            /**
             * 出流 TPS
             * @member
             * @type {number}
             */
            this["tpsOut"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            /**
             * 最后更新时间
             * @member
             * @type {string}
             */
            this["lastUpdated"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * 描述
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("routes" in $$source)) {
            /**
             * 路由信息
             * @member
             * @type {TopicRouteItem[]}
             */
            this["routes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TopicItem}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("routes" in $$parsedSource) {
            $$parsedSource["routes"] = $$createField12_0($$parsedSource["routes"]);
        }
        return new TopicItem(/** @type {Partial<TopicItem>} */($$parsedSource));
    }
}

/**
 * TopicMessageType 消息类型
 * @readonly
 * @enum {string}
 */
export const TopicMessageType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MessageTypeNormal: "Normal",
    MessageTypeFIFO: "FIFO",
    MessageTypeDelay: "Delay",
};

/**
 * TopicPerm Topic 权限
 * @readonly
 * @enum {string}
 */
export const TopicPerm = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PermRW: "RW",
    PermR: "R",
    PermW: "W",
    PermDeny: "DENY",
};

/**
 * TopicRouteItem Topic 路由条目
 */
export class TopicRouteItem {
    /**
     * Creates a new TopicRouteItem instance.
     * @param {Partial<TopicRouteItem>} [$$source = {}] - The source object to create the TopicRouteItem.
     */
    constructor($$source = {}) {
        if (!("broker" in $$source)) {
            /**
             * Broker 名称
             * @member
             * @type {string}
             */
            this["broker"] = "";
        }
        if (!("brokerAddr" in $$source)) {
            /**
             * Broker 地址
             * @member
             * @type {string}
             */
            this["brokerAddr"] = "";
        }
        if (!("readQueue" in $$source)) {
            /**
             * 读队列数
             * @member
             * @type {number}
             */
            this["readQueue"] = 0;
        }
        if (!("writeQueue" in $$source)) {
            /**
             * 写队列数
             * @member
             * @type {number}
             */
            this["writeQueue"] = 0;
        }
        if (!("perm" in $$source)) {
            /**
             * 权限
             * @member
             * @type {TopicPerm}
             */
            this["perm"] = TopicPerm.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicRouteItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TopicRouteItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopicRouteItem(/** @type {Partial<TopicRouteItem>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = BrokerNode.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = GroupSubscription.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = GroupClient.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = TopicRouteItem.createFrom;
const $$createType11 = $Create.Array($$createType10);
